-- Accounts and sub-users (see IDENTITY-DESIGN.md).
--
-- Introduces the ACCOUNT as the tenant boundary: billing, payment
-- methods and invoices attach to an account, users are logins scoped to
-- exactly one account (AWS model), and projects become cost centres
-- owned by the account rather than by a user.
--
-- DESTRUCTIVE: truncates all customer data. Applied 2026-08-04 when the
-- database held only smoke-test rows (14 users, 27 instances, 25 usage
-- records — all generated by scripts/production-smoke-test.sh). Do NOT
-- apply this to a database with real customers; it would need a
-- backfill migration instead, creating a personal account per user.

BEGIN;

-- ---------------------------------------------------------------
-- 1. Clear test data. Order matters only for readability; CASCADE
--    handles the dependencies.
-- ---------------------------------------------------------------
TRUNCATE billing.usage_records, billing.invoices, billing.payment_methods,
         compute.instances,
         auth.api_keys, auth.sessions, auth.projects, auth.users
    RESTART IDENTITY CASCADE;

-- ---------------------------------------------------------------
-- 2. Accounts — the tenant boundary
-- ---------------------------------------------------------------
CREATE TABLE auth.accounts (
    id             UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    -- 10 digits, randomly generated (sequential numbers would leak how
    -- many customers exist). Displayed grouped: 4815-1623-42
    account_number VARCHAR(12) UNIQUE NOT NULL,
    -- DNS-safe, globally unique; forms the sub-user sign-in URL
    -- console.teepin.com/<alias>. Permanent once claimed.
    alias          VARCHAR(63) UNIQUE NOT NULL,
    type           VARCHAR(20) NOT NULL CHECK (type IN ('personal','organization')),
    display_name   VARCHAR(255) NOT NULL,

    -- Organization-only; NULL for personal accounts until converted.
    legal_name     VARCHAR(255),
    tax_id         VARCHAR(64),
    billing_email  VARCHAR(255),
    billing_address JSONB,
    country        CHAR(2),

    status         VARCHAR(20) NOT NULL DEFAULT 'active'
                   CHECK (status IN ('active','suspended','closed')),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_accounts_alias  ON auth.accounts(alias);
CREATE INDEX idx_accounts_status ON auth.accounts(status);

CREATE TRIGGER update_accounts_updated_at BEFORE UPDATE ON auth.accounts
    FOR EACH ROW EXECUTE FUNCTION auth.update_updated_at_column();

-- ---------------------------------------------------------------
-- 3. Users belong to exactly one account
-- ---------------------------------------------------------------
ALTER TABLE auth.users
    ADD COLUMN account_id UUID NOT NULL REFERENCES auth.accounts(id) ON DELETE CASCADE,
    -- NULL for the account owner (signs in with a globally unique
    -- email); set for sub-users, who sign in with alias + username.
    ADD COLUMN username   VARCHAR(64),
    ADD COLUMN role       VARCHAR(20) NOT NULL DEFAULT 'owner'
               CHECK (role IN ('owner','admin','member','viewer')),
    ADD COLUMN status     VARCHAR(20) NOT NULL DEFAULT 'active'
               CHECK (status IN ('active','disabled')),
    -- Present from the start so email verification can be switched on
    -- later as a config flag rather than another migration
    -- (deferred 2026-08-04 — see IDENTITY-DESIGN.md item 4).
    ADD COLUMN email_verified_at TIMESTAMPTZ,
    ADD COLUMN mfa_secret        VARCHAR(255),
    ADD COLUMN mfa_enabled_at    TIMESTAMPTZ;

-- Sub-user usernames are unique WITHIN an account, not globally:
-- alice@acme.com may exist in several accounts.
CREATE UNIQUE INDEX idx_users_account_username
    ON auth.users(account_id, username) WHERE username IS NOT NULL;

-- Exactly one owner per account.
CREATE UNIQUE INDEX idx_users_account_owner
    ON auth.users(account_id) WHERE role = 'owner';

CREATE INDEX idx_users_account ON auth.users(account_id);

-- ---------------------------------------------------------------
-- 4. Projects belong to accounts (cost centres), not to users
-- ---------------------------------------------------------------
ALTER TABLE auth.projects
    ADD COLUMN account_id UUID NOT NULL REFERENCES auth.accounts(id) ON DELETE CASCADE;

CREATE INDEX idx_projects_account ON auth.projects(account_id);

-- Project slugs were GLOBALLY unique, which would stop a second
-- account ever creating a project called "production". Scope
-- uniqueness to the account, and exclude soft-deleted rows so a name
-- can be reused after deletion.
ALTER TABLE auth.projects DROP CONSTRAINT IF EXISTS projects_slug_key;

CREATE UNIQUE INDEX idx_projects_account_slug
    ON auth.projects(account_id, slug) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX idx_projects_account_name
    ON auth.projects(account_id, name) WHERE deleted_at IS NULL;

-- Per-project access for member-role users; owners and admins see all
-- projects in their account and need no rows here.
CREATE TABLE auth.project_access (
    user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    project_id UUID NOT NULL REFERENCES auth.projects(id) ON DELETE CASCADE,
    role       VARCHAR(20) NOT NULL DEFAULT 'member'
               CHECK (role IN ('member','viewer')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, project_id)
);

-- ---------------------------------------------------------------
-- 5. Denormalise account_id onto resources
--    Tenancy checks filter on account_id directly — never trusting a
--    project_id alone, and never needing a join to authorise a request.
-- ---------------------------------------------------------------
ALTER TABLE compute.instances
    ADD COLUMN account_id UUID NOT NULL REFERENCES auth.accounts(id) ON DELETE CASCADE;
CREATE INDEX idx_instances_account ON compute.instances(account_id);

ALTER TABLE billing.usage_records
    ADD COLUMN account_id UUID NOT NULL REFERENCES auth.accounts(id) ON DELETE CASCADE;
CREATE INDEX idx_usage_account ON billing.usage_records(account_id);
-- Billing summary groups by account, then project, then resource type.
CREATE INDEX idx_usage_account_project ON billing.usage_records(account_id, project_id, resource_type);

ALTER TABLE billing.invoices
    ADD COLUMN account_id UUID NOT NULL REFERENCES auth.accounts(id) ON DELETE CASCADE;
CREATE INDEX idx_invoices_account ON billing.invoices(account_id);

ALTER TABLE billing.payment_methods
    ADD COLUMN account_id UUID NOT NULL REFERENCES auth.accounts(id) ON DELETE CASCADE;
CREATE INDEX idx_payment_methods_account ON billing.payment_methods(account_id);

COMMIT;
