// Copyright 2026 TEEPIN Project
// Licensed under the Apache License, Version 2.0

// Package agent.v1 defines the contract between the TEEPIN control
// plane (AWS) and the cluster agents running beside GPU capacity.
//
// Direction matters: the AGENT dials OUT to the control plane and holds
// the stream open. Nothing inbound is exposed on the GPU node, so the
// Kubernetes API server stays firewalled. This is the pattern used by
// io.net workers, GitHub Actions runners and Tailscale.
//
// The control plane holds NO Kubernetes credentials. It decides what
// should exist (placement, billing, tenancy); the agent decides how to
// make it so (pods, services, ingresses) and reports what is actually
// running. Where the two disagree, the agent's report wins — it observes
// reality.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: agent/v1/agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ClusterAgent_Connect_FullMethodName = "/teepin.agent.v1.ClusterAgent/Connect"
)

// ClusterAgentClient is the client API for ClusterAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterAgentClient interface {
	// Connect establishes the long-lived control channel. The agent opens
	// it and sends Register as the first message; the control plane then
	// pushes Commands and the agent replies with Events on the same
	// stream. One connection multiplexes commands, status reports,
	// inventory and log streams (HTTP/2).
	//
	// On disconnect the agent reconnects with exponential backoff and
	// jitter, then re-registers and resends full inventory — the control
	// plane treats every reconnect as a fresh source of truth.
	Connect(ctx context.Context, opts ...grpc.CallOption) (ClusterAgent_ConnectClient, error)
}

type clusterAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterAgentClient(cc grpc.ClientConnInterface) ClusterAgentClient {
	return &clusterAgentClient{cc}
}

func (c *clusterAgentClient) Connect(ctx context.Context, opts ...grpc.CallOption) (ClusterAgent_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &ClusterAgent_ServiceDesc.Streams[0], ClusterAgent_Connect_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &clusterAgentConnectClient{stream}
	return x, nil
}

type ClusterAgent_ConnectClient interface {
	Send(*AgentMessage) error
	Recv() (*ControlMessage, error)
	grpc.ClientStream
}

type clusterAgentConnectClient struct {
	grpc.ClientStream
}

func (x *clusterAgentConnectClient) Send(m *AgentMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clusterAgentConnectClient) Recv() (*ControlMessage, error) {
	m := new(ControlMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClusterAgentServer is the server API for ClusterAgent service.
// All implementations must embed UnimplementedClusterAgentServer
// for forward compatibility
type ClusterAgentServer interface {
	// Connect establishes the long-lived control channel. The agent opens
	// it and sends Register as the first message; the control plane then
	// pushes Commands and the agent replies with Events on the same
	// stream. One connection multiplexes commands, status reports,
	// inventory and log streams (HTTP/2).
	//
	// On disconnect the agent reconnects with exponential backoff and
	// jitter, then re-registers and resends full inventory — the control
	// plane treats every reconnect as a fresh source of truth.
	Connect(ClusterAgent_ConnectServer) error
	mustEmbedUnimplementedClusterAgentServer()
}

// UnimplementedClusterAgentServer must be embedded to have forward compatible implementations.
type UnimplementedClusterAgentServer struct {
}

func (UnimplementedClusterAgentServer) Connect(ClusterAgent_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedClusterAgentServer) mustEmbedUnimplementedClusterAgentServer() {}

// UnsafeClusterAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterAgentServer will
// result in compilation errors.
type UnsafeClusterAgentServer interface {
	mustEmbedUnimplementedClusterAgentServer()
}

func RegisterClusterAgentServer(s grpc.ServiceRegistrar, srv ClusterAgentServer) {
	s.RegisterService(&ClusterAgent_ServiceDesc, srv)
}

func _ClusterAgent_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterAgentServer).Connect(&clusterAgentConnectServer{stream})
}

type ClusterAgent_ConnectServer interface {
	Send(*ControlMessage) error
	Recv() (*AgentMessage, error)
	grpc.ServerStream
}

type clusterAgentConnectServer struct {
	grpc.ServerStream
}

func (x *clusterAgentConnectServer) Send(m *ControlMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clusterAgentConnectServer) Recv() (*AgentMessage, error) {
	m := new(AgentMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClusterAgent_ServiceDesc is the grpc.ServiceDesc for ClusterAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "teepin.agent.v1.ClusterAgent",
	HandlerType: (*ClusterAgentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ClusterAgent_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent/v1/agent.proto",
}
